#
# Created by MikBac on 11.12.2022
#
version: "3.4"
services:
  kafka-bitnami:
    image: 'bitnami/kafka:3.3.1'
    hostname: bitnami-kafka
    restart: unless-stopped
    ports:
      - '9192:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9192,EXTERNAL://bitnami-kafka:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka-network
  kouncil-ui:
    image: 'consdata/kouncil:1.4'
    restart: unless-stopped
    ports:
      - '9080:8080'
    environment:
      - bootstrapServers=bitnami-kafka:9094
    networks:
      - kafka-network
    depends_on:
      - kafka-bitnami
networks:
  kafka-network: