#
# Created by MikBac on 18.12.2022
#
# ---------------------------------------------------------------------------------------------------------
# The following solution with replacement (plugin-rewritebody) is only TEMPORARY for version 1.4 of Kouncil
# and will be changed when the proxy starts working properly in Kouncil
# ---------------------------------------------------------------------------------------------------------
#
version: "3.4"
services:
  kafka-bitnami:
    image: 'bitnami/kafka:3.3.1'
    hostname: bitnami-kafka
    restart: unless-stopped
    ports:
      - '9192:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9192,EXTERNAL://bitnami-kafka:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - kafka-network
  traefik-proxy:
    image: "traefik:v3.0"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--experimental.plugins.plugin-rewritebody.modulename=github.com/traefik/plugin-rewritebody"
      - "--experimental.plugins.plugin-rewritebody.version=v0.3.1"
    ports:
      - "9082:80"
      - "9081:8080"
    networks:
      - kafka-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  kouncil-ui:
    image: 'consdata/kouncil:1.4'
    container_name: "kouncil-ui"
    restart: unless-stopped
    environment:
      - bootstrapServers=bitnami-kafka:9094
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.kouncil_ui.loadbalancer.server.port=8080"
      - "traefik.http.routers.kouncil_ui.rule=PathPrefix(`/kouncil-ui`)"
      - "traefik.http.routers.kouncil_ui.middlewares=kouncil_ui_strip, kouncil_ui_rewrite"
      - "traefik.http.middlewares.kouncil_ui_strip.stripprefix.prefixes=/kouncil-ui"
      - "traefik.http.middlewares.kouncil_ui_rewrite.plugin.plugin-rewritebody.rewrites[0].regex=<base href=\"/\">"
      - "traefik.http.middlewares.kouncil_ui_rewrite.plugin.plugin-rewritebody.rewrites[0].replacement=<base href=\"/kouncil-ui/\">"
      - "traefik.http.middlewares.kouncil_ui_rewrite.plugin.plugin-rewritebody.rewrites[1].regex=/api/"
      - "traefik.http.middlewares.kouncil_ui_rewrite.plugin.plugin-rewritebody.rewrites[1].replacement=/kouncil-ui/api/"
    networks:
      - kafka-network
    depends_on:
      - kafka-bitnami
      - traefik-proxy
networks:
  kafka-network: